on: [push]
name: push
jobs:
  test:
    strategy:
      matrix:
        python: [3.9, 3.8, 3.7]
        os: [ubuntu-20.04, macos-10.15, windows-2019]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1.2.0
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python}}
      - name: Install Requirements
        run: |
          pip install -r dev-requirements.txt
      - name: Install Scriptenv
        run: |
          pip install -e .
      - name: Run Unit Tests
        run: |
          pytest
      - name: Run Integration Tests
        run: |
          python -c "import scriptenv; scriptenv.requires('requests==2.25.1'); import requests; print(requests.__version__)"
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1.2.0
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Requirements
        run: |
          pip install wheel==0.36.2
      - name: Build Wheel
        run: |
          python setup.py bdist_wheel
      - name: Install Wheel
        run: |
          pip install dist/*.whl
      - name: Test Installation
        run: |
          python -c "import scriptenv"
      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist
  release:
    runs-on: ubuntu-20.04
    needs: [test, build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1.2.0
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Download Wheel
        uses: actions/download-artifact@v2
        with:
          name: wheel
          path: dist
      - name: Publish Latest GitHub Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          gh release delete latest --yes
          gh release create latest ./dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
